FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04

RUN apt-get update && apt-get -y install --no-install-recommends \
  build-essential cmake cmake-curses-gui git google-perftools graphviz \
  less libtool-bin pkg-config python3 valgrind wget
