FROM mcr.microsoft.com/devcontainers/base:debian

RUN apt-get update && apt-get -y install --no-install-recommends \
  build-essential cmake cmake-curses-gui git graphviz \
  less libtool-bin pkg-config python3 valgrind wget
